---
all:
  children:
    webservers:
      hosts:
        web1:
          ansible_host: "{{ lookup('env', 'PRODUCTION_SERVER_IP') }}"
          ansible_user: "{{ lookup('env', 'PRODUCTION_SERVER_USER') }}"
          ansible_ssh_private_key_file: "{{ lookup('env', 'PRODUCTION_SSH_KEY_PATH') }}"
      vars:
        app_name: emergency-healthcare
        docker_image: "{{ lookup('env', 'DOCKER_IMAGE') }}" 