apiVersion: apps/v1
kind: Deployment
metadata:
  name: emergency-healthcare
  labels:
    app: emergency-healthcare
spec:
  replicas: 2
  selector:
    matchLabels:
      app: emergency-healthcare
  template:
    metadata:
      labels:
        app: emergency-healthcare
    spec:
      containers:
        - name: emergency-healthcare
          image: emergency-healthcare:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              name: http
          env:
            - name: NODE_ENV
              value: production
            - name: NEXT_PUBLIC_SUPABASE_URL
              valueFrom:
                secretKeyRef:
                  name: emergency-healthcare-secrets
                  key: NEXT_PUBLIC_SUPABASE_URL
            - name: NEXT_PUBLIC_SUPABASE_ANON_KEY
              valueFrom:
                secretKeyRef:
                  name: emergency-healthcare-secrets
                  key: NEXT_PUBLIC_SUPABASE_ANON_KEY
            - name: NEXT_PUBLIC_GOOGLE_MAPS_API_KEY
              valueFrom:
                secretKeyRef:
                  name: emergency-healthcare-secrets
                  key: NEXT_PUBLIC_GOOGLE_MAPS_API_KEY
          resources:
            limits:
              cpu: 1000m
              memory: 2Gi
            requests:
              cpu: 500m
              memory: 1Gi
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5 