apiVersion: apps/v1
kind: Deployment
metadata:
  name: emergency-app
  labels:
    app: emergency-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: emergency-app
  template:
    metadata:
      labels:
        app: emergency-app
    spec:
      containers:
      - name: emergency-app
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html-content
          mountPath: /usr/share/nginx/html
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.2"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: html-content
        configMap:
          name: emergency-app-html
---
apiVersion: v1
kind: Service
metadata:
  name: emergency-app
spec:
  selector:
    app: emergency-app
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: emergency-app-html
data:
  index.html: |
    <!DOCTYPE html>
    <html>
      <head>
        <title>Emergency Healthcare Dashboard</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <style>
          body {
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
            line-height: 1.6;
            color: #333;
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
          }
          h1 {
            background-color: #1e40af;
            color: white;
            padding: 20px;
            border-radius: 5px;
          }
          .card {
            background-color: #f8f9fa;
            border-radius: 5px;
            padding: 20px;
            margin: 20px 0;
            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
          }
          .success {
            color: #0d6efd;
            font-weight: bold;
          }
        </style>
      </head>
      <body>
        <h1>Emergency Healthcare Dashboard</h1>
        <div class="card">
          <h2>Kubernetes Deployment</h2>
          <p class="success">✅ Successfully deployed to Kubernetes!</p>
          <p>Running on Kubernetes with monitoring and high availability.</p>
        </div>
      </body>
    </html>
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: emergency-app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: emergency.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: emergency-app
            port:
              number: 80 